load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test",
    srcs = glob(["**/*.cc"]),
    deps = [
        "//:metron",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:private"],
)

cc_test(
    name = "non_metric_test",
    srcs = glob(["core/non_metric/*.cc"]),
    deps = [
        "//:metron",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:private"],
)

cc_test(
    name = "metric_test",
    srcs = glob(["core/metric/*.cc"]),
    deps = [
        "//:metron",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:private"],
)